### ISSUE TITLE
ImagePullBackOff node-problem-detector:v0.8.11

### ISSUE THREAD

**Issue by BassOfLion** [deliveryhero/helm-charts#378]
When upgrading from chart version 2.2.2 to 2.2.4 pod hangs in ImagePullBackOff state because newer image is not found:

`Failed to pull image "k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.11": rpc error: code = NotFound desc = failed to pull and unpack image "k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.11": failed to resolve reference "k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.11": k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.11: not found`

`docker pull k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.11` locally fails as well.

**Comment by max-rocket-internet** [comment]
https://github.com/kubernetes/node-problem-detector/issues/692
https://github.com/deliveryhero/helm-charts/issues/372
https://github.com/deliveryhero/helm-charts/issues/376

**Comment by zestrells** [comment]
@BassOfLion This should now be solved 😄 https://github.com/deliveryhero/helm-charts/pull/379#event-7370838731

**Comment by BassOfLion** [comment]
@zestrells unfortunately it still doesn't work. Image not found:

```
docker pull k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.11
Error response from daemon: manifest for k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.11 not found: manifest unknown: Failed to fetch "v0.8.11" from request "/v2/node-problem-detector/node-problem-detector/manifests/v0.8.11".
```
I solved my issue by upgrading helm chart to v2.2.5 which was released recently. It uses v0.8.12 of node-problem detector.
